name: Format (prettier)

on:
  pull_request:
    paths:
      - "**.css"
      - "**.js"
      - "**.json"

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: npm ci
        env:
          CI: true

      - name: Run formatter
        run: npm run format

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: reformat'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
